name: CI/CD
on:
  push:
    branches:
      - timofey

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: yarn install
      - name: Build Docker Image
        run: |
          docker-compose up -d --build
          docker-compose down
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
      - name: Deploy
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          sshpass -p "$SERVER_PASSWORD" \
            scp -o StrictHostKeyChecking=no -r dist/* \
            $SERVER_USER@$SERVER_HOST:$TARGET_DIR
      - name: Restart nginx
        run: |
          sshpass -p "$SERVER_PASSWORD" \
          ssh -o StrictHostKeyChecking=no \
          $SERVER_USER@$SERVER_HOST \
          "sudo systemctl restart nginx"
